# Generated by Django 3.0.2 on 2020-01-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('powermove', models.TextField()),
                ('experience', models.IntegerField()),
                ('out_of_order', models.BooleanField()),
                ('avatar', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Danceoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battles', models.ManyToManyField(to='robots.Battle')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='r1',
            field=models.ForeignKey(limit_choices_to={'out_of_order': False}, on_delete=django.db.models.deletion.CASCADE, related_name='robot1', to='robots.Robot'),
        ),
        migrations.AddField(
            model_name='battle',
            name='r2',
            field=models.ForeignKey(limit_choices_to={'out_of_order': False}, on_delete=django.db.models.deletion.CASCADE, related_name='robot2', to='robots.Robot'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robots.Robot'),
        ),
    ]
